{ =============================================================================
  Database.Dialect.Firebird - Dialecto Firebird VERSION-AWARE (TDialectFirebird)

  Project:        ProvidersORM
  ProjectVersion: 3.0.0
  ModuleVersion:  3.0.0
  FileVersion:    1.9.0
  Company:        CSL Tech Solutions
  Author:         Claiton de Souza Linhares
  Date:           27/07/2026

  Onda 5.2 (2-D - OBRIGATORIO version-aware; SUBSTITUI o TVariableType
  estatico de Commons.Types, que so cobria 2.5.9):
    fb25: SMALLINT p/ boolean, generator+trigger p/ identity (SchemaSync 5.5),
          identificadores 31 bytes, ROWS m TO n;
    fb30: +BOOLEAN/IDENTITY nativos, +OFFSET..FETCH;
    fb40: +DECFLOAT/INT128, identificadores 63 chars;
    fb50: +RETURNING multi-linha.
  Gotchas ja apurados (4.2c): identificador que comeca por '_' exige aspas;
  SELECT sem FROM e invalido (usar RDB$DATABASE).

  Changelog (file):
  - 1.9.0 (27/07/2026): conformidade F5 (onda C6, #4) - FunctionsSQL override:
    RDB$FUNCTIONS.RDB$FUNCTION_NAME (ASchema ignorado - Firebird nao tem
    schemas; espelho de ProceduresSQL).
  - 1.8.0 (25/07/2026): F5-FU.1 (populacao de IsIdentity por dialecto, ADITIVO) -
    IdentityColumnsSQL override: RDB$RELATION_FIELDS.RDB$IDENTITY_TYPE (FB3.0+,
    GENERATED BY DEFAULT/ALWAYS AS IDENTITY) gated por Supports(scIdentity) -
    fb25 (generator+trigger classico, sem coluna IDENTITY nativa) devolve ''
    (version-aware, mesmo principio de ColumnTypeFor/ckIdentity).
  - 1.7.0 (18/07/2026): Onda D (bug-578) - UniquesSQL/IndexesSQL passam a aceitar
    o nome da tabela tanto LITERAL (criada com aspas = case preservado/minusculas)
    como UPPERCASE (sem aspas = default Firebird), via '(TRIM(nome)=literal OR
    TRIM(nome)=UPPER)' em vez do 'RDB$RELATION_NAME = UPPER(...)' fixo (que nunca
    casava tabelas quoted-lowercase). Capabilities DDL (scAlterColumn/scDropColumn/
    scRenameColumn/scForeignKeys/scViews/scStoredProcedures/scUserFunctions/scCheck)
    + facetas FieldAddSQL/FieldDropSQL/FieldRenameSQL/TableRenameSQL/ViewCreateSQL.
  - 1.6.0 (16/07/2026): Onda 5.5-B (ADITIVO) - scUnique adicionado as
    capabilities (Firebird suporta ALTER ADD CONSTRAINT ... UNIQUE, AddUniqueSQL
    fica na BASE). UniquesSQL override: RDB$RELATION_CONSTRAINTS filtrado por
    RDB$CONSTRAINT_TYPE = 'UNIQUE'. IndexesSQL override: RDB$INDICES por
    RDB$RELATION_NAME.
  - 1.5.0 (15/07/2026): Onda 6-f Estagio 1 (I10, ADITIVO) - ProceduresSQL
    override: RDB$PROCEDURES.RDB$PROCEDURE_NAME (ASchema ignorado - Firebird
    nao tem schemas, mesma semantica dos restantes metodos deste dialecto).
    CallProcedureSQL override: 'EXECUTE PROCEDURE <proc> :p0, :p1, ...' (sem
    parenteses). LinkedServersSQL fica na BASE (Firebird nao tem o conceito
    nativo).
  - 1.4.0 (15/07/2026): Onda 6-e Estagio 3 (I13, ADITIVO) - FunctionSQL
    override: LENGTH -> CHAR_LENGTH(x) (Firebird nao tem LENGTH); SUBSTRING ->
    sintaxe propria SUBSTRING(x FROM p [FOR n]) (Firebird NAO aceita a forma
    com virgulas da base ANSI).
  - 1.3.0 (15/07/2026): Onda 6-d PARTE 2 (I24, ADITIVO) - ColumnDescriptionSQL
    override: RDB$RELATION_FIELDS.RDB$DESCRIPTION (BLOB SUB_TYPE TEXT,
    preenchido via COMMENT ON COLUMN); Firebird nao tem schemas (ASchema
    ignorado, mesma semantica dos restantes metodos deste dialecto).
  - 1.2.0 (14/07/2026): Onda 6-a (F5 revisao, modernizacao AQB/EMS - I23,
    ADITIVO) - capabilities ESTATICAS (presentes em TODAS as versoes do
    nosso piso fb25+) scUpsert (UPDATE OR INSERT, desde FB 2.1)/scMerge
    (MERGE, desde FB 2.1)/scSequences (GENERATOR/SEQUENCE, sempre existiu)/
    scArrays (tipo ARRAY nativo de coluna, desde FB1)/scRecursiveCTE (WITH
    RECURSIVE, desde FB 2.1). Capability VERSION-AWARE nova (reusa o enum
    TFirebirdVersion ja existente, 2-D): scWindowFunctions (fb30+, funcoes
    analiticas/OVER). scJSON fica OFF em todas as versoes (Firebird nao tem
    tipo JSON nativo; FB4/5 tem so funcoes utilitarias pontuais, insuficiente
    p/ a capability completa - decisao documentada). scFullText fica OFF (sem
    FTS nativo, exige addon Lucene externo).
  - 1.1.0 (14/07/2026): Fatia B-e (continuacao Onda 4, revisao F5) - override
    de CreateDatabaseSQL/DropDatabaseSQL: sintaxe ISQL propria do Firebird -
    CREATE DATABASE recebe o PATH como STRING LITERAL (aspas SIMPLES), nao
    um identificador QuoteIdentifier; DROP DATABASE nao recebe argumento
    (opera sobre a conexao ATIVA). Corolario bug-315 (Database.Dialect.MySQL) -
    esta unit nunca chamara RTL directo antes; SysUtils/System.SysUtils
    adicionado ao uses da implementation so para Trim/StringReplace.
  - 1.0.0 (12/07/2026): versao inicial (Onda 5.2).
  ============================================================================= }
unit Database.Dialect.Firebird;

{$I ../../../ORM.Defines.inc}

{$IF DEFINED(FPC)}
  {$MODE DELPHI}
{$ENDIF}

interface

{$IFDEF USE_DATABASE}

uses
  Commons.Types,
  Commons.Database.Types,
  Commons.Database.Consts,
  Databases.Interfaces,
  Database.Dialect;

type
  TDialectFirebird = class(TDialect)
  strict private
    FServerVersion: TFirebirdVersion;
  strict protected
    procedure Setup; override;
  public
    class function New(const AVersion: TFirebirdVersion): IDialect;
    function ServerVersion: TFirebirdVersion;
    function ColumnTypeFor(const AKind: TSQLColumnKind; const ASize: Integer = 0;
      const AScale: Integer = 0): string; override;
    function CreateDatabaseSQL(const AName: string): string; override;
    function DropDatabaseSQL(const AName: string): string; override;
    function ColumnDescriptionSQL(const ATable, ASchema: string): string; override;
    function IdentityColumnsSQL(const ATableName, ASchema: string): string; override;
    function FunctionSQL(const AName: string; const AArgs: array of string): string; override;
    function ProceduresSQL(const ASchema: string): string; override;
    function FunctionsSQL(const ASchema: string): string; override;
    function ViewsSQL(const ASchema: string): string; override;
    function CallProcedureSQL(const AProcName: string; const AArgCount: Integer): string; override;
    function UniquesSQL(const ATable, ASchema: string): string; override;
    function IndexesSQL(const ATable, ASchema: string): string; override;
    { Onda D - COLUMN: Firebird usa ADD/DROP SEM 'COLUMN'; RENAME via ALTER COLUMN a TO b. }
    function FieldAddSQL(const ATable, AColumn, AColumnType: string;
      const ANotNull: Boolean): string; override;
    function FieldDropSQL(const ATable, AColumn: string): string; override;
    function FieldRenameSQL(const ATable, AOldName, ANewName: string): string; override;
    { Onda D - Firebird nao suporta RENAME de tabela -> ''. }
    function TableRenameSQL(const AOldName, ANewName: string): string; override;
    function ViewCreateSQL(const AName, ASelectSQL: string; const AOrReplace: Boolean): string; override;
    { Onda F1 - builder de rotinas (procedure/function SEM parenteses quando sem
      parametros; corpo BEGIN..END com ';' interno - estilo PSQL). }
    function RoutineDefCreateSQL(const ADef: IRoutineDefinition): string; override;
    { Onda F3 - triggers (FOR table ACTIVE, multi-evento OR, drop sem IF EXISTS). }
    function TriggersSQL(const ASchema: string): string; override;
    function TriggerDefCreateSQL(const ADef: ITriggerDefinition): string; override;
    function TriggerDropSQL(const AName, ATable: string; const AIfExists: Boolean): string; override;
  end;

{$ENDIF}

implementation

{$IFDEF USE_DATABASE}

uses
{$IFDEF FPC}
  SysUtils;
{$ELSE}
  System.SysUtils;
{$ENDIF}

class function TDialectFirebird.New(const AVersion: TFirebirdVersion): IDialect;
var
  LDialect: TDialectFirebird;
begin
  LDialect := TDialectFirebird.Create(dtFireBird);
  LDialect.FServerVersion := AVersion;
  LDialect.Setup; // re-executa com a versao definida
  Result := LDialect;
end;

function TDialectFirebird.ServerVersion: TFirebirdVersion;
begin
  Result := FServerVersion;
end;

procedure TDialectFirebird.Setup;
begin
  FCapabilities := [scCTE, scDerivedTables, scUnion, scUnionAll, scReturning,
    scConcatPipes, scRowsClause,
    { Onda 6-a (I23) - sempre presentes desde o nosso piso (fb25+) }
    scUpsert, scMerge, scSequences, scArrays, scRecursiveCTE];
  { Onda 5.5-B (ADITIVO) - scUnique incondicional: todos os engines suportam
    unicidade (Firebird via ALTER ADD CONSTRAINT ... UNIQUE). }
  FCapabilities := FCapabilities + [scUnique];
  { Onda D - DDL: Firebird suporta alter/drop/rename column, FK, views, proc/func,
    check; NAO tem DROP..IF EXISTS nativo nem RENAME de tabela. }
  FCapabilities := FCapabilities + [scAlterColumn, scDropColumn, scRenameColumn,
    scForeignKeys, scViews, scStoredProcedures, scUserFunctions, scCheck];
  FPagination := psRowsTo; // uniforme 2.5 - 5.0
  FMaxIdentLen := 31;
  case FServerVersion of
    fb30: FCapabilities := FCapabilities + [scBoolean, scIdentity, scOffsetFetch,
            scWindowFunctions];
    fb40: FCapabilities := FCapabilities + [scBoolean, scIdentity, scOffsetFetch,
            scDecFloat, scWindowFunctions];
    fb50: FCapabilities := FCapabilities + [scBoolean, scIdentity, scOffsetFetch,
            scDecFloat, scReturningMulti, scWindowFunctions];
  end;
  if FServerVersion >= fb40 then
    FMaxIdentLen := 63;
  case FServerVersion of
    fb25: FVersionText := 'Firebird 2.5';
    fb30: FVersionText := 'Firebird 3.0';
    fb40: FVersionText := 'Firebird 4.0';
    fb50: FVersionText := 'Firebird 5.0';
  end;
end;

function TDialectFirebird.ColumnTypeFor(const AKind: TSQLColumnKind;
  const ASize: Integer; const AScale: Integer): string;
begin
  case AKind of
    ckBoolean:
      if FServerVersion >= fb30 then
        Result := 'BOOLEAN'
      else
        Result := 'SMALLINT'; // 0/1 (2.5.9)
    ckIdentity:
      if FServerVersion >= fb30 then
        Result := 'INTEGER GENERATED BY DEFAULT AS IDENTITY'
      else
        Result := 'INTEGER'; // generator+trigger gerados pelo SchemaSync (5.5)
    ckText:     Result := 'BLOB SUB_TYPE TEXT';
    ckBlob:     Result := 'BLOB SUB_TYPE BINARY';
    ckDateTime: Result := 'TIMESTAMP';
  else
    Result := inherited ColumnTypeFor(AKind, ASize, AScale);
  end;
end;

function TDialectFirebird.RoutineDefCreateSQL(const ADef: IRoutineDefinition): string;
var
  LName, LParams, LBody, LType: string;
  LPs: TRoutineParamArray;
  I: Integer;
begin
  { Firebird (PSQL): parenteses SO quando ha parametros (sem params -> sem '()');
    procedure -> AS BEGIN..END; function -> RETURNS t AS BEGIN RETURN expr; END.
    Tipo via ColumnTypeFor (SSOT). }
  Result := '';
  if (ADef = nil) or (Trim(ADef.Name) = '') then
    Exit;
  LName := QuoteIdentifier(Trim(ADef.Name));
  LPs := ADef.Params;
  LParams := '';
  for I := 0 to High(LPs) do
  begin
    if LParams <> '' then LParams := LParams + ', ';
    LParams := LParams + QuoteIdentifier(Trim(LPs[I].Name)) + ' ' +
      ColumnTypeFor(LPs[I].Kind, LPs[I].Size);
  end;
  if LParams <> '' then
    LParams := ' (' + LParams + ')';
  if ADef.Kind = rkFunction then
  begin
    LType := ColumnTypeFor(ADef.ReturnKind, ADef.ReturnSize);
    case ADef.BodyMode of
      rbmRaw:    LBody := ADef.BodyText;
      rbmReturn: LBody := 'BEGIN RETURN ' + ADef.BodyText + '; END';
    else
      LBody := 'BEGIN RETURN NULL; END';
    end;
    Result := 'CREATE FUNCTION ' + LName + LParams + ' RETURNS ' + LType + ' AS ' + LBody;
  end
  else
  begin
    case ADef.BodyMode of
      rbmRaw: LBody := ADef.BodyText;
    else
      LBody := 'BEGIN EXIT; END';
    end;
    Result := 'CREATE PROCEDURE ' + LName + LParams + ' AS ' + LBody;
  end;
end;

function TDialectFirebird.CreateDatabaseSQL(const AName: string): string;
begin
  { Firebird: sintaxe ISQL propria - CREATE DATABASE recebe o PATH do
    ficheiro como STRING LITERAL (aspas simples), NAO um identificador
    QuoteIdentifier (Fatia B-e). Aspas simples internas escapadas duplicando-
    as (sintaxe padrao de string literal SQL). }
  Result := '';
  if Trim(AName) = '' then
    Exit;
  Result := 'CREATE DATABASE ''' +
    StringReplace(Trim(AName), '''', '''''', [rfReplaceAll]) + ''';';
end;

function TDialectFirebird.DropDatabaseSQL(const AName: string): string;
begin
  { Firebird: DROP DATABASE nao recebe argumento - opera sobre a conexao
    ACTIVA (tem de estar ligado exactamente a base a apagar; sintaxe classica
    ISQL). AName so participa da validacao (nao vazio). }
  Result := '';
  if Trim(AName) = '' then
    Exit;
  Result := 'DROP DATABASE;';
end;

function TDialectFirebird.ColumnDescriptionSQL(const ATable, ASchema: string): string;
begin
  { Firebird: RDB$RELATION_FIELDS.RDB$DESCRIPTION (BLOB SUB_TYPE TEXT,
    preenchido via COMMENT ON COLUMN - sintaxe classica ISQL); Firebird nao
    tem schemas (ASchema ignorado, mesma semantica dos restantes metodos deste
    dialecto - ver CreateSchemaSQL/DropSchemaSQL na BASE, scSchemas OFF). 2
    colunas POSICIONAIS - column_name, description (COALESCE evita NULL).
    Nomes de tabela Firebird sao guardados em MAIUSCULAS quando nao citados
    (identificador nao delimitado - convencao do proprio ISQL). }
  Result :=
    'SELECT TRIM(rf.RDB$FIELD_NAME) AS column_name, ' +
    'COALESCE(rf.RDB$DESCRIPTION, '''') AS description ' +
    'FROM RDB$RELATION_FIELDS rf ' +
    'WHERE rf.RDB$RELATION_NAME = ''' +
    StringReplace(UpperCase(Trim(ATable)), '''', '''''', [rfReplaceAll]) + ''' ' +
    'ORDER BY rf.RDB$FIELD_POSITION';
end;

function TDialectFirebird.IdentityColumnsSQL(const ATableName, ASchema: string): string;
begin
  { F5-FU.1 - Firebird: RDB$RELATION_FIELDS.RDB$IDENTITY_TYPE (FB3.0+, GENERATED
    BY DEFAULT/ALWAYS AS IDENTITY) so existe nas versoes com scIdentity ON (fb30+,
    ver Setup/case FServerVersion acima); fb25 (generator+trigger classico, sem
    coluna IDENTITY nativa no catalogo) devolve '' - version-aware, mesmo
    principio de ColumnTypeFor/ckIdentity acima (nao ha catalogo equivalente
    fiavel em fb25). ASchema ignorado - Firebird nao tem schemas (mesma
    semantica de ColumnDescriptionSQL/ProceduresSQL acima). 1 coluna POSICIONAL
    - nome da coluna; TRIM remove o padding fixo do RDB$; nomes de tabela
    Firebird sao guardados em MAIUSCULAS quando nao citados. }
  Result := '';
  if not Supports(scIdentity) then
    Exit;
  Result :=
    'SELECT TRIM(rf.RDB$FIELD_NAME) AS column_name ' +
    'FROM RDB$RELATION_FIELDS rf ' +
    'WHERE rf.RDB$RELATION_NAME = ''' +
    StringReplace(UpperCase(Trim(ATableName)), '''', '''''', [rfReplaceAll]) + ''' ' +
    'AND rf.RDB$IDENTITY_TYPE IS NOT NULL';
end;

function TDialectFirebird.FunctionSQL(const AName: string; const AArgs: array of string): string;
begin
  { Firebird: sem LENGTH (usa CHAR_LENGTH); SUBSTRING NAO aceita a forma com
    virgulas da base ANSI - exige a sintaxe propria FROM/FOR (Onda 6-e
    Estagio 3, I13). }
  if SameText(Trim(AName), 'LENGTH') then
  begin
    if Length(AArgs) >= 1 then
      Result := 'CHAR_LENGTH(' + AArgs[0] + ')'
    else
      Result := 'CHAR_LENGTH()';
    Exit;
  end;
  if SameText(Trim(AName), 'SUBSTRING') then
  begin
    if Length(AArgs) >= 3 then
      Result := 'SUBSTRING(' + AArgs[0] + ' FROM ' + AArgs[1] + ' FOR ' + AArgs[2] + ')'
    else if Length(AArgs) = 2 then
      Result := 'SUBSTRING(' + AArgs[0] + ' FROM ' + AArgs[1] + ')'
    else
      Result := inherited FunctionSQL(AName, AArgs);
    Exit;
  end;
  Result := inherited FunctionSQL(AName, AArgs);
end;

function TDialectFirebird.ProceduresSQL(const ASchema: string): string;
begin
  { Firebird: RDB$PROCEDURES.RDB$PROCEDURE_NAME; ASchema ignorado - Firebird
    nao tem schemas (mesma semantica dos restantes metodos deste dialecto -
    ver ColumnDescriptionSQL acima); 1 coluna POSICIONAL - nome da procedure
    (Onda 6-f Estagio 1, I10). Nomes de procedure Firebird sao guardados em
    MAIUSCULAS quando nao citados; TRIM remove o padding fixo do RDB$. }
  Result :=
    'SELECT TRIM(rp.RDB$PROCEDURE_NAME) AS procedure_name ' +
    'FROM RDB$PROCEDURES rp ' +
    'ORDER BY rp.RDB$PROCEDURE_NAME';
end;

function TDialectFirebird.TriggersSQL(const ASchema: string): string;
begin
  { Firebird: RDB$TRIGGERS sem os do sistema (RDB$SYSTEM_FLAG 0/NULL). ASchema
    ignorado. 1 coluna [0]=trigger name; TRIM remove o padding CHAR do RDB$. }
  Result :=
    'SELECT TRIM(rt.RDB$TRIGGER_NAME) AS trigger_name ' +
    'FROM RDB$TRIGGERS rt ' +
    'WHERE (rt.RDB$SYSTEM_FLAG = 0 OR rt.RDB$SYSTEM_FLAG IS NULL) ' +
    'ORDER BY rt.RDB$TRIGGER_NAME';
end;

function TDialectFirebird.TriggerDefCreateSQL(const ADef: ITriggerDefinition): string;
var
  LName, LTable, LTiming, LEvents, LBody: string;
begin
  { Firebird: CREATE TRIGGER n FOR t ACTIVE [BEFORE|AFTER] ev [OR ev...] AS
    BEGIN...END. Sem FOR EACH ROW (triggers de tabela sao row-level implicito);
    sem INSTEAD OF (so em views) -> cai em AFTER. }
  Result := '';
  if (ADef = nil) or (Trim(ADef.Name) = '') or (Trim(ADef.OnTable) = '') then
    Exit;
  LName  := QuoteIdentifier(Trim(ADef.Name));
  LTable := QuoteIdentifier(Trim(ADef.OnTable));
  if ADef.Timing = ttBefore then
    LTiming := 'BEFORE'
  else
    LTiming := 'AFTER';
  LEvents := TriggerEventsClause(ADef.Events, ' OR ');
  if ADef.BodyMode = tbmRaw then
    LBody := 'AS BEGIN ' + ADef.BodyText + ' END'
  else
    LBody := 'AS BEGIN END';
  Result := 'CREATE TRIGGER ' + LName + ' FOR ' + LTable + ' ACTIVE ' +
    LTiming + ' ' + LEvents + ' ' + LBody;
end;

function TDialectFirebird.TriggerDropSQL(const AName, ATable: string; const AIfExists: Boolean): string;
begin
  { Firebird: DROP TRIGGER name (SEM IF EXISTS, SEM ON table); a idempotencia
    fica a cargo do lancador (TriggerExists antes do drop). }
  Result := '';
  if Trim(AName) = '' then
    Exit;
  Result := 'DROP TRIGGER ' + QuoteIdentifier(Trim(AName));
end;

function TDialectFirebird.FunctionsSQL(const ASchema: string): string;
begin
  { Firebird (Onda C6, #4): RDB$FUNCTIONS.RDB$FUNCTION_NAME (espelho de
    ProceduresSQL); ASchema ignorado - Firebird nao tem schemas; TRIM remove
    o padding fixo do RDB$. 1 coluna POSICIONAL - nome da function. }
  Result :=
    'SELECT TRIM(rf.RDB$FUNCTION_NAME) AS function_name ' +
    'FROM RDB$FUNCTIONS rf ' +
    'ORDER BY rf.RDB$FUNCTION_NAME';
end;

function TDialectFirebird.ViewsSQL(const ASchema: string): string;
begin
  { Firebird nao tem information_schema: views = RDB$RELATIONS com RDB$VIEW_SOURCE
    preenchido (RDB$RELATION_TYPE=1). ASchema ignorado. 1 coluna [0]=view name;
    TRIM remove o padding CHAR do RDB$. }
  Result :=
    'SELECT TRIM(RDB$RELATION_NAME) FROM RDB$RELATIONS ' +
    'WHERE RDB$VIEW_SOURCE IS NOT NULL';
end;

function TDialectFirebird.CallProcedureSQL(const AProcName: string; const AArgCount: Integer): string;
var
  I: Integer;
  LArgs: string;
begin
  { Firebird: EXECUTE PROCEDURE <proc> :p0, :p1, ... (sem parenteses);
    AProcName vazio -> '' (Onda 6-f Estagio 1, I10). }
  if Trim(AProcName) = '' then
    Exit('');
  LArgs := '';
  for I := 0 to AArgCount - 1 do
  begin
    if LArgs <> '' then LArgs := LArgs + ', ';
    LArgs := LArgs + ':p' + IntToStr(I);
  end;
  Result := 'EXECUTE PROCEDURE ' + QuoteIdentifier(Trim(AProcName));
  if LArgs <> '' then
    Result := Result + ' ' + LArgs;
end;

function TDialectFirebird.UniquesSQL(const ATable, ASchema: string): string;
var
  LLit: string;
begin
  { Onda D (bug-578): aceitar tanto o nome literal (tabela criada com aspas =
    case preservado, minusculas) como o UPPERCASE (sem aspas = default Firebird).
    TRIM porque RDB$RELATION_NAME e CHAR(31/63) space-padded. }
  Result := '';
  if Trim(ATable) = '' then
    Exit;
  LLit := StringReplace(Trim(ATable), '''', '''''', [rfReplaceAll]);
  Result := 'SELECT TRIM(rc.RDB$CONSTRAINT_NAME) FROM RDB$RELATION_CONSTRAINTS rc' +
    ' WHERE rc.RDB$CONSTRAINT_TYPE = ''UNIQUE'' AND (TRIM(rc.RDB$RELATION_NAME) = ''' +
    LLit + ''' OR TRIM(rc.RDB$RELATION_NAME) = ''' + UpperCase(LLit) + ''')';
end;

function TDialectFirebird.IndexesSQL(const ATable, ASchema: string): string;
var
  LLit: string;
begin
  { Onda D (bug-578): mesmo padrao OR literal/UPPERCASE de UniquesSQL. }
  Result := '';
  if Trim(ATable) = '' then
    Exit;
  LLit := StringReplace(Trim(ATable), '''', '''''', [rfReplaceAll]);
  Result := 'SELECT TRIM(i.RDB$INDEX_NAME) FROM RDB$INDICES i' +
    ' WHERE (TRIM(i.RDB$RELATION_NAME) = ''' + LLit +
    ''' OR TRIM(i.RDB$RELATION_NAME) = ''' + UpperCase(LLit) + ''')';
end;

{ Onda D - COLUMN: Firebird nao usa a keyword 'COLUMN' no ADD/DROP; o RENAME
  faz-se com 'ALTER TABLE t ALTER COLUMN a TO b' (nao 'RENAME COLUMN'). O ALTER
  de tipo herda a base ('ALTER COLUMN col TYPE x' - Firebird aceita). }

function TDialectFirebird.FieldAddSQL(const ATable, AColumn, AColumnType: string;
  const ANotNull: Boolean): string;
begin
  Result := '';
  if (Trim(ATable) = '') or (Trim(AColumn) = '') then Exit;
  Result := 'ALTER TABLE ' + QuoteIdentifier(Trim(ATable)) + ' ADD ' +
    QuoteIdentifier(Trim(AColumn)) + ' ' + AColumnType;
  if ANotNull then Result := Result + ' NOT NULL';
end;

function TDialectFirebird.FieldDropSQL(const ATable, AColumn: string): string;
begin
  Result := '';
  if (Trim(ATable) = '') or (Trim(AColumn) = '') then Exit;
  Result := 'ALTER TABLE ' + QuoteIdentifier(Trim(ATable)) + ' DROP ' +
    QuoteIdentifier(Trim(AColumn));
end;

function TDialectFirebird.FieldRenameSQL(const ATable, AOldName, ANewName: string): string;
begin
  Result := '';
  if (Trim(ATable) = '') or (Trim(AOldName) = '') or (Trim(ANewName) = '') then Exit;
  Result := 'ALTER TABLE ' + QuoteIdentifier(Trim(ATable)) + ' ALTER COLUMN ' +
    QuoteIdentifier(Trim(AOldName)) + ' TO ' + QuoteIdentifier(Trim(ANewName));
end;

function TDialectFirebird.TableRenameSQL(const AOldName, ANewName: string): string;
begin
  Result := ''; { Firebird nao suporta RENAME de tabela. }
end;

function TDialectFirebird.ViewCreateSQL(const AName, ASelectSQL: string; const AOrReplace: Boolean): string;
begin
  { Firebird: CREATE OR ALTER VIEW (nao OR REPLACE). }
  Result := '';
  if (Trim(AName) = '') or (Trim(ASelectSQL) = '') then Exit;
  if AOrReplace then
    Result := 'CREATE OR ALTER VIEW ' + QuoteIdentifier(Trim(AName)) + ' AS ' + ASelectSQL
  else
    Result := 'CREATE VIEW ' + QuoteIdentifier(Trim(AName)) + ' AS ' + ASelectSQL;
end;

{$ENDIF}

end.
