{ =============================================================================
  GraphQL.Server.OrmResolvers - ORM-backed field resolvers (FASE 13, wave 13A.4-c)

  Binds the schema generated by GraphQL.Schema.Factory (13A.3) to the ORM via
  IQueryBuilder, and installs the resolvers with InstallOrmResolvers:

    - root single  <type>(id: ID!)  -> SELECT * FROM t WHERE pk = :id
    - root list    <type>List(...)  -> SELECT * FROM t [LIMIT/OFFSET]
    - navigation   <T>.<nav>        -> BATCH SELECT * FROM target WHERE pk IN (fks)

  The navigation resolver is a DATALOADER: ResolveBatch gets EVERY source row of
  the current level at once, collects the distinct FK values and issues ONE
  WhereIn query, then distributes the rows back - so a nested navigation costs 1
  query per level, not one per row (anti-N+1, decision 5).

  DI is transparent: the resolver only holds an IConnection (pooled or direct is
  invisible). Structure/naming reuse GraphQL.Schema.Factory's exposed helpers.
  Query-side only in this wave; mutation resolvers (insert/update/delete via
  ExecuteMutation) are a documented backlog item.

  Project:        ProvidersORM
  ProjectVersion: 3.0.0
  ModuleVersion:  1.0.0
  FileVersion:    1.0.0
  Company:        CSL Tech Solutions
  Author:         Claiton de Souza Linhares
  Date:           12/08/2026

  Changelog (file):
  - 1.0.0 (12/08/2026): FASE 13 wave 13A.4-c - DataSetRowToValue, root (single/
    list) + navigation (batched WhereIn) ORM resolvers, InstallOrmResolvers.
  ============================================================================= }

unit GraphQL.Server.OrmResolvers;

{$IF DEFINED(FPC)}
  {$MODE DELPHI}
{$ENDIF}

interface

{$I ../../../ORM.Defines.inc}

{$IF DEFINED(USE_GRAPHQL) AND DEFINED(USE_DATABASE) AND DEFINED(USE_QUERY_BUILDER)}

uses
{$IF DEFINED(FPC)}
  SysUtils,
  Variants,
  DB,
{$ELSE}
  System.SysUtils,
  System.Variants,
  Data.DB,
{$ENDIF}
  Connections.Interfaces,
  Databases.Interfaces,
  Database,
  Database.CatalogReader,
  Commons.Types,
  Commons.Database.Types,
  GraphQL.Value,
  GraphQL.Executor,
  GraphQL.Schema,
  GraphQL.Schema.Types,
  GraphQL.Schema.Factory;

type
  { Resolves a root query field. FSingle: <type>(id) -> one row; else list. }
  TGraphQLOrmRootResolver = class(TInterfacedObject, IGraphQLResolver)
  private
    FConn: IConnection;
    FTable: string;
    FSchema: string;
    FPk: string;
    FSingle: Boolean;
  public
    constructor Create(const AConn: IConnection; const ATable, ASchema, APk: string;
      ASingle: Boolean);
    function ResolveBatch(const ASources: TGraphQLValueArray;
      AContext: TGraphQLResolveContext): TGraphQLValueArray;
  end;

  { Resolves a navigation field (FK -> referenced object) for ALL source rows in a
    single WhereIn query (dataloader). }
  TGraphQLOrmNavResolver = class(TInterfacedObject, IGraphQLResolver)
  private
    FConn: IConnection;
    FTargetTable: string;
    FSchema: string;
    FTargetPk: string;
    FFkColumn: string;
  public
    constructor Create(const AConn: IConnection;
      const ATargetTable, ASchema, ATargetPk, AFkColumn: string);
    function ResolveBatch(const ASources: TGraphQLValueArray;
      AContext: TGraphQLResolveContext): TGraphQLValueArray;
  end;

{ Attaches ORM resolvers to the root and navigation fields of a schema produced
  by TGraphQLSchemaFactory.FromMetadata over the SAME catalog + schema. }
procedure InstallOrmResolvers(const ASchema: IGraphQLSchema;
  const AMeta: ICatalogReader; const AConnection: IConnection;
  const ACatalogSchema: string = '');

{$ENDIF}

implementation

{$IF DEFINED(USE_GRAPHQL) AND DEFINED(USE_DATABASE) AND DEFINED(USE_QUERY_BUILDER)}

{ Reads the CURRENT row of ADataSet into an object value (column -> scalar). }
function DataSetRowToValue(ADataSet: TDataSet;
  AArena: TGraphQLValueArena): TGraphQLValue;
var
  I: Integer;
  LField: TField;
begin
  Result := AArena.NewObject;
  for I := 0 to ADataSet.FieldCount - 1 do
  begin
    LField := ADataSet.Fields[I];
    if LField.IsNull then
      Result.SetField(LField.FieldName, AArena.NewNull)
    else
      Result.SetField(LField.FieldName, AArena.NewScalar(LField.Value));
  end;
end;

{ TGraphQLOrmRootResolver }

constructor TGraphQLOrmRootResolver.Create(const AConn: IConnection;
  const ATable, ASchema, APk: string; ASingle: Boolean);
begin
  inherited Create;
  FConn := AConn;
  FTable := ATable;
  FSchema := ASchema;
  FPk := APk;
  FSingle := ASingle;
end;

function TGraphQLOrmRootResolver.ResolveBatch(const ASources: TGraphQLValueArray;
  AContext: TGraphQLResolveContext): TGraphQLValueArray;
var
  LQb: IQueryBuilder;
  LDs: TDataSet;
  LList: TGraphQLValue;
  LId, LLimit, LOffset: TGraphQLValue;
begin
  AContext.Executor.QueryCount := AContext.Executor.QueryCount + 1;
  SetLength(Result, Length(ASources)); // root has exactly one source
  LQb := TDatabase.QueryBuilder(FConn).Select('*').From(FTable, FSchema);
  if FSingle then
  begin
    LId := AContext.Arg('id');
    if (LId <> nil) and (LId.Kind = gvkScalar) then
      LQb := LQb.Where(FPk, LId.Scalar)
    else
      LQb := LQb.Where(FPk, Null);
    LDs := LQb.Execute;
    try
      if (LDs <> nil) and (not LDs.Eof) then
        Result[0] := DataSetRowToValue(LDs, AContext.Arena)
      else
        Result[0] := AContext.Arena.NewNull;
    finally
      LDs.Free;
    end;
  end
  else
  begin
    LLimit := AContext.Arg('limit');
    LOffset := AContext.Arg('offset');
    if (LLimit <> nil) and (LLimit.Kind = gvkScalar) then
      LQb := LQb.Limit(LLimit.Scalar);
    if (LOffset <> nil) and (LOffset.Kind = gvkScalar) then
      LQb := LQb.Offset(LOffset.Scalar);
    LDs := LQb.Execute;
    try
      LList := AContext.Arena.NewList;
      if LDs <> nil then
      begin
        LDs.First;
        while not LDs.Eof do
        begin
          LList.AddItem(DataSetRowToValue(LDs, AContext.Arena));
          LDs.Next;
        end;
      end;
      Result[0] := LList;
    finally
      LDs.Free;
    end;
  end;
end;

{ TGraphQLOrmNavResolver }

constructor TGraphQLOrmNavResolver.Create(const AConn: IConnection;
  const ATargetTable, ASchema, ATargetPk, AFkColumn: string);
begin
  inherited Create;
  FConn := AConn;
  FTargetTable := ATargetTable;
  FSchema := ASchema;
  FTargetPk := ATargetPk;
  FFkColumn := AFkColumn;
end;

function TGraphQLOrmNavResolver.ResolveBatch(const ASources: TGraphQLValueArray;
  AContext: TGraphQLResolveContext): TGraphQLValueArray;
var
  LKeys: array of Variant;
  LMapKey: array of string;
  LMapVal: TGraphQLValueArray;
  LFk, LRow: TGraphQLValue;
  LDs: TDataSet;
  S, I: Integer;
  LKeyStr: string;
  LPkVal: Variant;

  function KeyKnown(const AKey: string): Boolean;
  var K: Integer;
  begin
    Result := False;
    for K := 0 to High(LMapKey) do
      if LMapKey[K] = AKey then Exit(True);
  end;

begin
  SetLength(Result, Length(ASources));
  { collect DISTINCT FK values across all sources }
  SetLength(LKeys, 0);
  for S := 0 to High(ASources) do
  begin
    LFk := nil;
    if ASources[S] <> nil then
      LFk := ASources[S].GetField(FFkColumn);
    if (LFk <> nil) and (LFk.Kind = gvkScalar) then
    begin
      LKeyStr := VarToStr(LFk.Scalar);
      if not KeyKnown('K' + LKeyStr) then
      begin
        SetLength(LKeys, Length(LKeys) + 1);
        LKeys[High(LKeys)] := LFk.Scalar;
        SetLength(LMapKey, Length(LMapKey) + 1);
        LMapKey[High(LMapKey)] := 'K' + LKeyStr; // placeholder; filled below
      end;
    end;
  end;

  if Length(LKeys) = 0 then
  begin
    for S := 0 to High(ASources) do
      Result[S] := AContext.Arena.NewNull;
    Exit;
  end;

  { ONE batched query for the whole level }
  AContext.Executor.QueryCount := AContext.Executor.QueryCount + 1;
  SetLength(LMapKey, 0);
  SetLength(LMapVal, 0);
  LDs := TDatabase.QueryBuilder(FConn).Select('*').From(FTargetTable, FSchema)
    .WhereIn(FTargetPk, LKeys).Execute;
  try
    if LDs <> nil then
    begin
      LDs.First;
      while not LDs.Eof do
      begin
        LRow := DataSetRowToValue(LDs, AContext.Arena);
        LPkVal := LDs.FieldByName(FTargetPk).Value;
        SetLength(LMapKey, Length(LMapKey) + 1);
        LMapKey[High(LMapKey)] := VarToStr(LPkVal);
        SetLength(LMapVal, Length(LMapVal) + 1);
        LMapVal[High(LMapVal)] := LRow;
        LDs.Next;
      end;
    end;
  finally
    LDs.Free;
  end;

  { distribute rows back to each source by FK value }
  for S := 0 to High(ASources) do
  begin
    Result[S] := AContext.Arena.NewNull;
    LFk := nil;
    if ASources[S] <> nil then
      LFk := ASources[S].GetField(FFkColumn);
    if (LFk = nil) or (LFk.Kind <> gvkScalar) then
      Continue;
    LKeyStr := VarToStr(LFk.Scalar);
    for I := 0 to High(LMapKey) do
      if LMapKey[I] = LKeyStr then
      begin
        Result[S] := LMapVal[I];
        Break;
      end;
  end;
end;

{ InstallOrmResolvers }

procedure InstallOrmResolvers(const ASchema: IGraphQLSchema;
  const AMeta: ICatalogReader; const AConnection: IConnection;
  const ACatalogSchema: string);
var
  LTables: TStringArray;
  T, I: Integer;
  LTypeName, LRootName, LPk, LBareTo, LToType, LNavName: string;
  LQueryType, LObjType: TGraphQLObjectType;
  LPks: TStringArray;
  LRels: TArray<TRelationInfo>;
  LField: TGraphQLFieldDef;
begin
  LQueryType := ASchema.QueryType;
  LTables := AMeta.TableNames(ACatalogSchema);
  for T := 0 to High(LTables) do
  begin
    LTypeName := GraphQLTypeNameForTable(LTables[T]);
    LRootName := GraphQLRootFieldName(LTypeName);
    LObjType := nil;
    if ASchema.FindType(LTypeName) is TGraphQLObjectType then
      LObjType := TGraphQLObjectType(ASchema.FindType(LTypeName));

    LPks := AMeta.PrimaryKeyColumns(LTables[T], ACatalogSchema);
    if Length(LPks) > 0 then
      LPk := LPks[0]
    else
      LPk := 'id';

    { root single + list }
    if LQueryType <> nil then
    begin
      LField := LQueryType.FindField(LRootName);
      if LField <> nil then
        LField.Resolver := TGraphQLOrmRootResolver.Create(
          AConnection, LTables[T], ACatalogSchema, LPk, True) as IGraphQLResolver;
      LField := LQueryType.FindField(LRootName + 'List');
      if LField <> nil then
        LField.Resolver := TGraphQLOrmRootResolver.Create(
          AConnection, LTables[T], ACatalogSchema, LPk, False) as IGraphQLResolver;
    end;

    { navigation fields (FK -> target object) }
    if LObjType <> nil then
    begin
      LRels := AMeta.ResolveFK(LTables[T], ACatalogSchema);
      for I := 0 to High(LRels) do
      begin
        LBareTo := GraphQLStripSchema(LRels[I].ToTable);
        LToType := GraphQLTypeNameForTable(LBareTo);
        LNavName := GraphQLRootFieldName(LToType);
        if LRels[I].Cardinality = rcOneToMany then
          Continue; // list navigation resolver is a backlog item (this wave: N:1)
        LField := LObjType.FindField(LNavName);
        if LField <> nil then
          LField.Resolver := TGraphQLOrmNavResolver.Create(
            AConnection, LBareTo, ACatalogSchema, LRels[I].ToColumn,
            LRels[I].FromColumn) as IGraphQLResolver;
      end;
    end;
  end;
end;

{$ENDIF}

end.
